### ISSUE TITLE
invite to the discord seems expired

### ISSUE THREAD

**Issue by thomwolf** [cuda-mode/resource-stream#7]
maybe need to refresh it

**Comment by andreaskoepf** [comment]
oops sry, should be refreshed now. Let me know in case it doesn't work.

**Comment by hsiming999** [comment]
I think the invite is expired again. @andreaskoepf could you refresh it? Thanks.

**Comment by andreaskoepf** [comment]
Temporary invite: https://discord.gg/cuda-mode-1189498204333543425

**Comment by andreaskoepf** [comment]
@hsiming999 thanks for reporting, should be fixed now.
